version: '3.4'

networks:
  derivco-network:
    driver: overlay

services:
  derivco:
    image: adolfodelsel/derivco
    build: ../.
    depends_on:
      - database
    command: /bin/bash to_test/docker-test.sh
    #volumes:
      #- ../:/opt/derivco
      #- /opt/derivco/_build
      #- /opt/derivco/assets
    ports:
      - 4000:4000
    networks:
      - derivco-network

  database:
    image: mariadb:10.1.41
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: football
      MYSQL_USER: derivco_user
      MYSQL_PASSWORD: derivco_pass
    ports:
      - 3306:3306
    networks:
      - derivco-network 
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10