version: '3.4'

networks:
  derivco-network:
    driver: overlay

services:
  derivco:
    image: adolfodelsel/derivco
    build: .
    depends_on:
      - database
    ports:
      - 4000
    environment:
     - SERVICE_PORTS=4000
    deploy:
      replicas: 3
      update_config:
        parallelism: 3
        delay: 10s
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - derivco-network

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - derivco
    environment:
      - BALANCE=leastconn
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - derivco-network
    deploy:
      placement:
        constraints: [node.role == manager]

  database:
    image: mariadb:10.1.41
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: football
      MYSQL_USER: derivco_user
      MYSQL_PASSWORD: derivco_pass
    ports:
      - 3306
    networks:
      - derivco-network 
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10